
server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA 정적 파일
  location / {
    try_files $uri /index.html;
  }

  # API 프록시 — /api 접두어를 그대로 유지해서 백엔드로 전달
  location /api/ {
    proxy_pass http://myapp-backend:8090;   # 이부분이랑 윗줄 슬레쉬 테스트 개발자 콘솔에서 8090으로 연결되게 해야함
    # <-- 뒤에 슬래시 붙이지 마세요
    proxy_http_version 1.1;


    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 5s;
    proxy_read_timeout    60s;
    proxy_send_timeout    60s;
  }
}
